application: bangmotivate
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.(gif|png|jpg|ico))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|ico))

- url: .*
  script: main.py

